import { StyleSheet } from 'react-native';
import Colors from '../../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.Background_color,
  },
  tabsContainer: {
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border_light,
  },
  genderTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  participantTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.bg_light,
  },
  tabActive: {
    backgroundColor: Colors.primary,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.text_light,
  },
  tabTextActive: {
    color: Colors.white,
  },
  statusTabs: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    gap: 8,
  },
  statusTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: Colors.bg_light,
    gap: 6,
  },
  statusTabActive: {
    backgroundColor: Colors.info_background,
  },
  statusTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.text_light,
  },
  statusTabTextActive: {
    color: Colors.primary,
  },
  liveIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.status_rejected,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    color: Colors.text_light,
    marginTop: 16,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text_dark,
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: Colors.text_light,
    textAlign: 'center',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  eventTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border_lighter,
  },
  eventTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: Colors.primary,
  },
  matchCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: Colors.shadow,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 3,
  },
  myMatchCard: {
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: Colors.match_my_team_background,
  },
  matchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border_light,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  matchNumberBadge: {
    backgroundColor: Colors.stats_background,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  matchNumberText: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.primary,
  },
  myMatchBadge: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  myMatchText: {
    fontSize: 10,
    fontWeight: '700',
    color: Colors.white,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.white,
    textTransform: 'uppercase',
  },
  livePulse: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.white,
  },
  teamsContainer: {
    marginBottom: 16,
  },
  teamBox: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 12,
  },
  teamName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text_dark,
  },
  scoreBox: {
    backgroundColor: Colors.bg_light,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    minWidth: 45,
    alignItems: 'center',
    justifyContent: 'center',
  },
  liveScoreBox: {
    backgroundColor: Colors.live_score_back,
    borderWidth: 2,
    borderColor: Colors.live_score_display,
  },
  winnerScoreBox: {
    backgroundColor: Colors.primary,
  },
  score: {
    fontSize: 24,
    fontWeight: '700',
    color: Colors.text_dark,
  },
  winnerScore: {
    color: Colors.white,
  },
  vsContainer: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  vsText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.text_lighter,
  },
  liveScoreIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.live_score_back,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.live_score_display,
  },
  liveScoreText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.live_score_text,
  },
  winnerBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.winner_background,
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    gap: 8,
  },
  winnerText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.winner_text,
    flex: 1,
  },
  drawBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.drawBanner,
    padding: 12,
    borderRadius: 12,
    marginBottom: 16,
    gap: 8,
  },
  drawText: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.text_light,
  },
  matchDetails: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.border_light,
    gap: 8,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailText: {
    fontSize: 13,
    color: Colors.text_light,
    flex: 1,
  },
  tapHintContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.border_lighter,
    gap: 4,
  },
  tapHint: {
    fontSize: 12,
    color: Colors.text_lighter,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    maxWidth: 500,
    height: '85%',
    backgroundColor: Colors.white,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
});