export const validationStrings = {
    NAME_REQUIRED : 'Name is required',
    MINIMUM_NAME_LENGTH : 'Name must be at least 3 characters long',
    NAME_ONLY_ALPHA : 'Name can contain only letters and spaces',
    EMAIL_REQUIRED : 'Email is required',
    EMAIL_ONLY_LOWERCASE : 'Email must be in lowercase only',
    VALID_EMAIL : 'Please enter a valid email address',
    PASSWORD_REQUIRED : 'Password is required',
    PASS_MIN_LENGTH : 'Password must be at least 10 characters long',
    PASS_UPPER_REQUIRED : 'Password must contain at least one uppercase letter (A-Z)',
    PASS_LOWER_REQUIRED : 'Password must contain at least one lowercase letter (a-z)',
    PASS_DIGIT_REQUIRED : 'Password must contain at least one number (0-9)',
    PASS_SPECIAL_REQUIRED : 'Password must contain at least one special character (@$!%*?&)',
    REGISTRATION_SUCCESS : 'Registration successful. Please login.',
    TITLE : 'Sports Carnival Management System',
    ADMIN_EMAIL : 'admin@gmail.com',
    ADMIN_PASS : '@Admin12345',
    ADMIN_TITLE : 'Admin Dashboard',
    ADMIN_ROLE : 'Manage users, events, reports',
    PARTICIPANT_TITLE : 'Welcome Participant',
    PARTICIPANT_ROLE : 'Explore and join events',
    ORGANISER_TITLE : 'Organizer Dashboard',
    ORGANISER_ROLE : 'Create & manage events',
    INVALID_CREDENTIALS : 'Invalid credentials',
    RESERVED_EMAIL : 'This email is reserved for admin',
    ADMIN_REG_FORBIDDEN : 'Admin registration is not allowed',
    EMAIL_EXISTS : 'Email already registered',
};