export const validationStrings = {
    NAME_REQUIRED : 'Name is required',
    MINIMUM_NAME_LENGTH : 'Name must be at least 3 characters long',
    NAME_ONLY_ALPHA : 'Name can contain only letters and spaces',
    EMAIL_REQUIRED : 'Email is required',
    EMAIL_ONLY_LOWERCASE : 'Email must be in lowercase only',
    VALID_EMAIL : 'Please enter a valid email address',
    PASSWORD_REQUIRED : 'Password is required',
    PASSWORD_SUGGESTION : 'Suggesting Strong Password',
    REGISTRATION_SUCCESS : 'Registration successful. Please login.',
    TITLE : 'Sports Carnival Management System',
    ADMIN_EMAIL : 'admin@gmail.com',
    ADMIN_PASS : '@Admin12345',
    ADMIN_TITLE : 'Admin Dashboard',
    ADMIN_ROLE : 'Manage users, events, reports',
    PARTICIPANT_TITLE : 'Welcome Participant',
    PARTICIPANT_ROLE : 'Explore and join events',
    ORGANISER_TITLE : 'Organizer Dashboard',
    ORGANISER_ROLE : 'Create & manage events',
    INVALID_CREDENTIALS : 'Invalid credentials',
    RESERVED_EMAIL : 'This email is reserved for admin',
    ADMIN_REG_FORBIDDEN : 'Admin registration is not allowed',
    EMAIL_EXISTS : 'Email already registered',
    EVENT_DETAILS : 'Formats         Registered Teams / Max Teams',
    ORGANIZER_ALERT : 'Assign Organizer, Open modal or picker to assign organizer',
    DELETE_COFIRMATION : 'Confirm Delete',
    DELETE_MSG : 'Are you sure you want to delete this event?',
    EVENT_NOT_EXISTS : 'Event not found',
    FORMAT_FULL : 'Format not available',
    REGISTRATION_FULL : 'Registration full',
    EVENT_MANAGE : 'Manage Events',
    MANAGE_USER : 'Manage Users',
    TEAM_MANAGE : 'Manage Teams',
    SCHEDULE_RESULT : 'Schedules & Results',
    REPORT : 'View Reports',
    CONFIG : 'System Configuration',
    ORG_EVENTS : 'My Events',
    TEAM_REG : 'Team Registrations',
    MY_TEAM : 'My Teams',
    VIEW_EVENTS : 'View Events',
    EVENT_TITLE : 'Event Title',
    GAMES : 'Football, Carrom',
    EVENT_DESCRIPTION : 'Event Description',
    DATE_FORMAT : 'YYYY-MM-DD',
};