export const validationStrings = {
  NAME_REQUIRED: 'Name is required',
  MINIMUM_NAME_LENGTH: 'Name must be at least 3 characters long',
  NAME_ONLY_ALPHA: 'Name can contain only letters and spaces',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_ONLY_LOWERCASE: 'Email must be in lowercase only',
  VALID_EMAIL: 'Please enter a valid email address',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_SUGGESTION: 'Suggesting Strong Password',
  DONT_HAVE_ACCOUNT : 'Dont have an account?',
  REGISTRATION_SUCCESS: 'Registration successful. Please login.',
  TEAM_CREATED_SUCCESS: 'Team created successfully',
  TEAM_DELETED_SUCCESS: 'Team deleted successfully',
  EVENT_CREATED_SUCCESS: 'Event created successfully!',
  EVENT_UPDATED_SUCCESS: 'Event updated successfully!',
  EVENT_DELETED_SUCCESS: 'Event deleted successfully',
  USER_DELETED_SUCCESS: 'User deleted successfully',
  REGISTRATION_APPROVED_SUCCESS: 'Registration approved successfully',
  REGISTRATION_REJECTED_SUCCESS: 'Registration rejected',
  REGISTRATION_CANCELLED_SUCCESS: 'Registration cancelled successfully',
  REGISTRATION_SUBMITTED_SUCCESS: 'Registration submitted successfully! You will be notified once approved by the organizer.',
  REG_NOT_FOUND: 'Registration not found',
  MATCHES_CREATED_SUCCESS: 'Match(es) created successfully',
  ERROR_TEAM_UPDATE: 'Error updating event registered teams:',
  ALREADY_REGISTERED: 'You are already registered for this format',
  LOGIN : 'Login',
  GENDER : 'Gender',
  UPDATE_EVENT : 'Update Event',
  MAX_FOR_TEAM_CREATION : 'Max participants for team formation',
  MAX_FOR_EACH_GENDER : 'Max participants for each gender category',
  SEARCH_PLACEHOLDER: 'Search by name, email, or event...',
  PENDING_REGISTRATION: 'pending registration',
  APPROVE_ALL: 'Approve All',
  NO_REGISTRATIONS_FOUND: 'No Registrations Found',
  ADJUST_SEARCH_FILTERS: 'Try adjusting your search or filters',
  NO_REGISTRATIONS_MATCH_FILTER: 'No registrations match the selected filter',
  READY_TO_CREATE_TEAMS: 'Ready to Create Teams',
  REJECT_REGISTRATION: 'Reject Registration',
  REASON_FOR_REJECTION_REQUIRED: 'Reason for Rejection *',
  ENTER_REJECTION_REASON: 'Enter reason for rejection...',
  REG_ERROR : 'Registration error:',
  LOADING_TEAMS: 'Loading teams...',
  SEARCH_EVENT_MEMBER: 'Search by event or member name...',
  TEAM_MEMBERS_LABEL: 'Team Members:',
  CREATED: 'Created:',
  BY: 'By:',
  NO_TEAMS_FOUND: 'No Teams Found',
  TRY_ADJUSTING_FILTERS: 'Try adjusting your filters',
  NO_TEAM_REGISTRATIONS: 'No team registrations yet',

  ALREADY_HAVE_ACCOUNT : ' Already have an account?',
  LOADING_USERS: 'Loading users...',
  SEARCH_NAME_EMAIL: 'Search by name or email...',
  TOTAL_USERS_LABEL: 'Total Users',
  ORGANIZERS: 'Organizers',
  PARTICIPANTS: 'Participants',
  JOINED: 'Joined:',
  NO_USERS_REGISTERED: 'No users registered yet',

  TITLE: 'Sports Carnival Management System',
  ADMIN_TITLE: 'Admin Dashboard',
  ADMIN_ROLE: 'Manage users, events, reports',
  PARTICIPANT_TITLE: 'Welcome Participant',
  PARTICIPANT_ROLE: 'Explore and join events',
  ORGANISER_TITLE: 'Organizer Dashboard',
  ORGANISER_ROLE: 'Create & manage events',
  LOGIN_FAILED : 'Login failed:',
  ADMIN_EMAIL: 'admin@gmail.com',
  ADMIN_PASS: 'Admin@12345',

  ADMIN: 'ADMIN',
  ORGANIZER: 'ORGANIZER',
  PARTICIPANT: 'PLAYER',

  ADMIN_PANEL: 'admin-panel-settings',
  EVENT: 'event',
  PART: 'PARTICIPANT',
  PERSON: 'person',
  CREATE_FIXTURES : 'Create Fixtures',
  EVENT_NOT_EXISTS: 'Event not found',
  FORMAT_FULL: 'Format not available',
  REGISTRATION_FULL: 'Registration full',
  EVENT_TITLE: 'Event Title',
  EVENT_DESCRIPTION: 'Event Description',
  EVENT_DES: 'Describe the event',
  EVENT_LOCATION: 'Event location',
  DATE_FORMAT: 'YYYY-MM-DD',
  MATCH_GET_ERROR: 'Error getting matches',
  MATCH_SAVING_ERROR: 'Error saving matches',
  MATCH_SAVE_FAIL: 'Failed to save matches',

  EVENT_MANAGE: 'Manage Events',
  MANAGE_USER: 'Manage Users',
  TEAM_MANAGE: 'Manage Teams',
  SCHEDULE_RESULT: 'Schedules & Results',
  REPORT: 'View Reports',
  CONFIG: 'System Configuration',
  ORG_EVENTS: 'My Events',
  TEAM_REG: 'Team Registrations',
  MY_TEAM: 'My Teams',
  VIEW_EVENTS: 'View Events',
  CREATE_TEAM : 'Create Team',

  INVALID_CREDENTIALS: 'Invalid credentials',
  RESERVED_EMAIL: 'This email is reserved for admin',
  ADMIN_REG_FORBIDDEN: 'Admin registration is not allowed',
  EMAIL_EXISTS: 'Email already registered',
  FAILED_TO_LOAD: 'Failed to load',
  FAILED_TO_LOAD_TEAMS: 'Failed to load teams',
  FAILED_TO_CREATE: 'Failed to create',
  FAILED_TO_UPDATE: 'Failed to update',
  FAILED_TO_DELETE: 'Failed to delete',
  FAILED_TO_APPROVE: 'Failed to approve',
  PASSWORD_RESET_SUCCESS : 'Password Reset Successful',
  FAILED_TO_REJECT: 'Failed to reject',

  TITLE_VALIDATION: 'Please enter event title',
  SPORT_TYPE: 'Please enter sport type',
  DEADLINE: 'Please select registration deadline',
  MATCH_DATE: 'Please select match date',
  LOCATION: 'Please enter event location',
  FOOSBALL_FORMAT: 'Foosball events must have 2v2 format',
  OTHER_SPORT_FORMAT: 'Please enable 1v1 format',
  MAX_MALE_1V1: 'Please enter valid max male participants for 1v1 format',
  MAX_FEMALE_1V1: 'Please enter valid max female participants for 1v1 format',
  MAX_MALE_2V2: 'Please enter valid max male participants for 2v2 format',
  MAX_FEMALE_2V2: 'Please enter valid max female participants for 2v2 format',
  EVEN_MALE_2V2: 'Max male participants must be an even number for 2v2 format',
  EVEN_FEMALE_2V2: 'Max female participants must be an even number for 2v2 format',
  LOGIN_REQUIRED: 'You must be logged in to create events',

  USER_APPROVAL_PENDING: 'Your account is pending admin approval',
  USER_APPROVAL_REJECTED: 'Your account has been rejected',
  DEADLINE_REACHED: 'Registration deadline has passed',
  EXTEND_DEADLINE: 'Extend Deadline',
  MALE_REGISTRATIONS: 'Male Registrations',
  FEMALE_REGISTRATIONS: 'Female Registrations',
  GENDER_LIMIT_REACHED: 'Gender category is full',
  CHESS_MIXED_ALLOWED: 'Males and females can compete together',


  ERROR: 'Error',
  SUCCESS: 'Success',
  WARNING: 'Warning',
  INFO: 'Info',
  CONFIRM: 'Confirm',

  DELETE_CONFIRMATION: 'Confirm Delete',
  DELETE_MESSAGE: (name: string) => `Are you sure you want to delete ${name}?`,
  DELETE_MSG: 'Are you sure you want to delete this event?',
  CONFIRM_DELETE_EVENT: 'Are you sure you want to delete this team?',
  LOGOUT_CONFIRMATION: 'Logout',
  LOGOUT_MSG: 'Are you sure you want to logout?',
  LOGOUT_ERROR: 'Logout error',

  ORGANIZER_ALERT: 'Assign Organizer, Open modal or picker to assign organizer',

  GAMES: 'Football, Carrom',

  NO_TEAMS_YET: 'No Teams Yet',
  NO_PARTICIPANTS_AVAILABLE: 'No Participants Available',
  APPROVED_TEAM_ASSIGNED : 'All approved participants have been assigned to teams',
  INSUFFICIENT_PARTICIPANTS: 'Insufficient Participants',
  TEAM_FULL: 'Team Full',
  TEAM_APPROVED_SUCCESSFULLY: 'Team approved successfully',
  INVALID_TEAM_SIZE: 'Invalid Team Size',
  REJECT_TEAM: 'Reject Team',
  REASON_FOR_REJECTION: 'Please provide a reason for rejection:',
  TEAM_APPROVAL_FAILED: 'Failed to approve team',
  MANUAL_TEAM_CREATE : 'Create Team Manually',
  TEAM_NOT_FOUND: 'Team not found',
  TEAM_GET_ERROR: 'Error getting teams',
  AUTO_GENERATE_MATCH : 'Auto-Generate All',
  MANUAL_CREATE : 'Manual Create',
  TEAMS_READY_FOR_MATCHES : 'teams ready for matches',
  GENERATE_MATCHES : 'Generate Matches',
  TEAM_DELETE_SUCCESS: 'Team deleted successfully',
  TEAM_DELETE_FAIL: 'Failed to delete team',
  TEAM_SAVING_ERROR: 'Error saving teams',

  NO_REGISTRATIONS_YET: 'No Registrations Yet',
  NO_PENDING_REGISTRATIONS: 'No Pending Registrations',
  REGISTRATION_PENDING: 'Registration Pending',
  REGISTRATION_APPROVED: 'Registration Approved',
  REGISTRATION_REJECTED: 'Registration Rejected',
  CANCEL_REGISTRATION: 'Cancel Registration',
  GET_REGISTRATION_ERROR: 'Error getting registrations',
  SAVE_REGISTRATION_ERROR: 'Error saving registrations',
  REJECTION_REASON : 'Rejection Reason:',


  NO_MATCHES_YET: 'No Matches Yet',
  INSUFFICIENT_TEAMS: 'Insufficient Teams',
  GENERATE_MATCHES: 'Generate Matches',
  FORMAT_NOT_FOUND: 'Format not found',
  MATCHES_NOT_FOUND: 'Match not found',
  ROUND_ROBIN: 'round-robin',
  KNOCKOUT: 'knockout',

  ERROR_GETTING_EVENTS: 'Error getting stored events:',
  ERROR_SAVING_EVENTS: 'Error saving events:',
  NO_EVENTS_AVAILABLE: 'No Events Available',
  NO_EVENTS_FOUND: 'No Events Found',
  NO_EVENTS_TODAY: 'No Events Today',
  NO_UPCOMING_EVENTS: 'No Upcoming Events',
  NO_EVENTS_CREATED_YET: 'No Events Created Yet',
  INIT_USERS_ERROR: 'Error initializing users:',
  GET_USERS_ERROR: 'Error getting users',
  SAVE_USERS_ERROR: 'Error saving users',

  NO_USERS_FOUND: 'No Users Found',
  TEAMMATE_NOT_FOUND: 'Teammate not found. Please ensure they are registered.',
  SAVE_USERS_FAILED: 'Failed to save users',
  USER_DELETED: 'User deleted successfully',
  FAILED_TO_DELETE_USER: 'Failed to delete user',
  USER_NOT_FOUND: 'User not found',
  SPORT_TYPE_TITLE : 'Sport Type *',
  DESCRIPTION : 'Description',
  REG_DEADLINE : 'Registration Deadline *',
  SELECT_DEADLINE : 'Select registration deadline',
  REG_CLOSES_ON_THIS_DAY : 'Registration closes on this date',
  MATCH_DATE_DISPLAY : 'Match Date *',
  FORMAT_DATE : 'Select match date',
  FOOSBALL_RULES : 'Foosball uses 2v2 format - Admin creates teams from individual registrations',
  INVALID_CURRENT_PASSWORD: 'Invalid current password',
  DELETE_ADMIN_FORBIDDEN: 'Cannot delete admin user',
  AUTH_ERROR: 'useAuth must be used inside AuthProvider',
  MATCH_INVALID: 'Match date cannot be before registration deadline',
  MATCH_VALID_REGISTRATION: 'Match date must be at least 1 day after registration deadline',
  PROVIDE_REASON: 'Please provide a reason',
  TEAM_REJECTED: 'Team rejected',
  REJECT_FAIL: 'Failed to reject team',

  SELECT_FORMAT: 'Please select a format',
  LOGIN_FIRST: 'Please login first',
  GENDER_UPDATE: 'Please update your profile with gender information',
  ENTER_TEAMMATE_NAME: 'Please enter teammate name',
  ENTER_TEAMMATE_EMAIL: 'Please enter teammate email',
  TEAMMATE_GENDER_MUST_BE_THERE: 'Teammate must have gender information in their profile',
  SAME_GENDER_TEAMMATE: 'Team members must be of the same gender for this event',
  REVIEW_PENDING: 'Registration submitted! Your team will be reviewed by the organizer.',
  REGISTER_FAIL: 'Failed to register for event',
  PLAYER_COUNT: '2 players per team',
  FORGOT_PASSWORD : 'Forgot Password',
  ENTER_REG_EMAIL_ID : 'Enter your registered email address',
  CANCEL: 'Cancel',
  DELETE: 'Delete',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  SUBMIT: 'Submit',
  SAVE: 'Save',
  EDIT: 'Edit',
  CREATE: 'Create',
  LOCATIONS : 'Location *',
  PART_LIMIT : 'Participant Limits *',
  OVO_FORMAT : '1v1 Format',
  TVT_FORMAT : '2v2 Format',
  INDIVIDUAL_MATCHS : 'Individual matches',
  MAX_MALE_PAR : 'Max Male Participants',
  TEAM_CREATE : 'Participants register individually - Admin creates teams',
  MAX_FEMALE_PAR : 'Max Female Participants',
  LIMIT_RULES : 'Must be even (e.g., 24 participants = 12 teams)',
  UPDATE: 'Update',
  VIEW: 'View',
  SEARCH: 'Search',
  FILTER: 'Filter',
  REFRESH: 'Refresh',
  LOADING: 'Loading...',
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  MALE_ICON : 'male',
  FEMALE_ICON : 'female',
  MIXED: 'MIXED',
  TRUE: 'true',

  TOTAL: 'Total',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  UPCOMING: 'Upcoming',
  COMPLETED: 'COMPLETED',
  IN_PROGRESS: 'IN_PROGRESS',
  ONGOING: 'Ongoing',
  SCHEDULED: 'SCHEDULED',
  CANCELLED: 'CANCELLED',
  CREATED_TEAMS : 'Created Teams',
  UNASSIGNED_PARTICIPANTS : 'Unassigned Participants',

  OR: 'OR',
  AND: 'AND',
  ALL: 'All',
  NONE: 'None',
  YES: 'Yes',
  NO: 'No',
  OK: 'OK',
  DONE: 'Done',
  BACK: 'Back',
  NEXT: 'Next',
  PREVIOUS: 'Previous',
  CLOSE: 'Close',
  OPEN: 'Open',
  SELECT: 'Select',
  SELECTED: 'Selected',
  REQUIRED: 'Required',
  OPTIONAL: 'Optional',
  UNASSIGNED : 'Unassigned',

  BROWSE_EVENTS_TITLE: 'Browse Events',
  BROWSE_EVENTS_SUBTITLE: 'Find events to join',
  MY_REGISTRATIONS_TITLE: 'My Registrations',
  MY_REGISTRATIONS_SUBTITLE: 'View registration status',
  MY_MATCHES_TITLE: 'My Matches',
  MY_MATCHES_SUBTITLE: 'View scheduled matches',
  MY_TEAMS_TITLE: 'My Teams',
  MY_TEAMS_SUBTITLE: 'View team assignments',

  ICON_EXPLORE: 'explore',
  ICON_ASSIGNMENT: 'assignment',
  ICON_TROPHY: 'emoji-events',
  ICON_GROUPS: 'groups',

  SAMPLE_EVENT_1_TITLE: 'Carrom Championship',
  SAMPLE_EVENT_1_DATE: 'Jan 27',
  SAMPLE_EVENT_1_TIME: '10:00 AM',
  SAMPLE_EVENT_1_SPORT: 'Carrom',

  SAMPLE_EVENT_2_TITLE: 'Table Tennis Open',
  SAMPLE_EVENT_2_DATE: 'Feb 03',
  SAMPLE_EVENT_2_TIME: '2:00 PM',
  SAMPLE_EVENT_2_SPORT: 'Table Tennis',

  SAMPLE_EVENT_3_TITLE: 'Badminton League',
  SAMPLE_EVENT_3_DATE: 'Feb 05',
  SAMPLE_EVENT_3_TIME: '9:00 AM',
  SAMPLE_EVENT_3_SPORT: 'Badminton',

  ADMIN_MSG: 'Welcome Back, Admin! 👋',
  ADMIN_NOTE: 'Manage your sports events and platform',
  TOTAL_EVENTS: 'Total Events',
  TOTAL_USERS: 'Total Users',
  TOTAL_REG: 'Registrations',
  QUICK_ACTIONS: 'Quick Actions',
  SELECT_EVENT: 'Select Event & Format',
  CHOOSE_EVENTS_FORMAT: 'Choose an event and format to create teams',

  UNKNOWN_EVENT: 'Unknown Event',
  FORMAT: 'Format:',
  DATE_TBD: 'Date TBD',
  LOCATION_TBD: 'Location TBD',
  REGISTERED: 'Registered:',
  TEAM_ASSIGNED: 'Team Assigned',
  REASON: 'Reason:',
  VIEW_EVENT: 'View Event',
  BROWSE_EVENTS: 'Browse Events',
  BROWSE_EVENTS_GET_STARTED: 'Browse events and register to get started',
  TEAMS_CREATED : 'Teams Created',
  LOADING_REGISTRATIONS: 'Loading registrations...',
  LOADING_MATCHES: 'Loading matches...',

  MATCH_NUMBER: 'Match #',
  VS: 'VS',
  ROLE : 'Role',
  YOU_WON: 'You Won!',
  OPPONENT_WON: 'Opponent Won',
  UPCOMING_MATCHES: 'Upcoming Matches',
  COMPLETED_MATCHES: 'Completed Matches',
  YOUR_SCHEDULED_MATCHES: 'Your scheduled matches will appear here',

  REGISTER_FOR_EVENT: 'Register for Event',
  SELECT_FORMAT_TITLE: 'Select Format',
  INDIVIDUAL_REGISTRATION_INFO: "You're registering individually. Teams will be created by the organizer after approval.",
  SPOTS: 'spots',
  FULL: 'FULL',
  YOUR_GENDER: 'Your Gender: ',
  WHAT_HAPPENS_NEXT: 'What happens next?',
  STEP_1: 'Your registration will be reviewed',
  STEP_2: 'Organizer approves participants',
  STEP_3: 'Organizer creates teams',
  STEP_4: 'Matches are scheduled',
  SUBMITTING: 'Submitting...',
  SUBMIT_REGISTRATION: 'Submit Registration',

  TEAMMATE_INFORMATION: 'Teammate Information',
  TEAMMATE_NAME_LABEL: 'Teammate Name *',
  TEAMMATE_EMAIL_LABEL: 'Teammate Email *',
  ENTER_TEAMMATE_NAME_PLACEHOLDER: 'Enter teammate name',
  ENTER_TEAMMATE_EMAIL_PLACEHOLDER: 'Enter teammate email',
  TEAMMATE_MUST_BE_REGISTERED: 'Your teammate must be registered on the platform and must have the same gender as you.',
  REGISTRATION_REVIEW_INFO: "Your registration will be reviewed by the event organizer. You'll be notified once approved.",
  SPOTS_LEFT: 'spots left',
  TEAMS_REGISTERED: 'teams registered',

  READY_TO_PLAY: 'Ready to Play? 🏆',
  JOIN_EXCITING_TOURNAMENTS: 'Join exciting tournaments and compete with others!',
  LOGOUT: 'Logout',
  EVENTS_JOINED: 'Events Joined',

  WINS: 'Wins',
  DISCOVER_NEW_EVENTS: 'Discover New Events',
  BROWSE_ALL_TOURNAMENTS: 'Browse all available tournaments and competitions',
  EXPLORE_NOW: 'Explore Now',
  SEE_ALL: 'See All',

  HELLO_ORGANIZER: 'Hello, {name}! 🎯',
  MAKE_EVENT_AMAZING: "Let's make your next event amazing",
  MY_EVENTS: 'My Events',
  TOTAL_REGISTRATIONS: 'Total Registrations',
  CREATE_NEW_EVENT: 'Create New Event',
  START_ORGANIZING: 'Start organizing your next tournament',
  MANAGEMENT: 'Management',
  RECENT_ACTIVITY: 'Recent Activity',

  NO_TEAMS_AVAILABLE: 'No Teams Available',
  VIEW_TEAM_ASSIGNMENTS: 'View team assignments',
  CAPTAIN: 'Captain',
  TEAMS: 'Teams',
  MEMBERS: 'Members',
  DIVIDER_DOT: '•',

  REGISTRATION_CLOSED: 'Registration Closed',
  REGISTRATION_CLOSED_MESSAGE: 'The registration deadline for this event has passed.',
  REGISTRATION_CLOSED_EXCLAIM: 'Registration closed!!!',
  REGISTRATION_OPEN_EXCLAIM: 'Registration open!!!',
  YOU_ARE_IN_TEAM: "You're In a Team!",
  TEAM_ASSIGNED_MESSAGE: "You've been assigned to a team for this event. Check \"My Teams\" to see details.",
  VIEW_MY_TEAMS: 'View My Teams',
  REGISTRATION_APPROVED_MESSAGE: "Your registration has been approved! You'll be assigned to a team soon.",
  VIEW_MY_REGISTRATIONS: 'View My Registrations',
  REGISTRATION_REVIEW_MESSAGE: 'Your registration is being reviewed by the admin.',
  VIEW_STATUS: 'View Status',
  REGISTRATION_REJECTED_MESSAGE: 'Your registration was not approved. You can try registering for a different format.',
  REGISTER_AGAIN: 'Register Again',
  REGISTRATION_DEADLINE_LABEL: 'Registration Deadline',
  MATCH_DATE_LABEL: 'Match Date',
  LOCATION_LABEL: 'Location',
  GENDER_RULES_LABEL: 'Gender Rules',
  MIXED_GENDER_ALLOWED: 'Mixed gender matches allowed',
  PARTICIPANT_REGISTRATION_TITLE: 'Participant Registration',
  INDIVIDUAL_PARTICIPANTS: 'Individual participants',
  PARTICIPANTS_ADMIN_CREATES_TEAMS: 'Participants (Admin creates teams)',
  MALE_PARTICIPANTS_LABEL: 'Male Participants',
  FEMALE_PARTICIPANTS_LABEL: 'Female Participants',
  REGISTERED_LABEL: 'registered',
  TOTAL_REGISTERED_LABEL: 'Total Registered',

  ALL_EVENTS_TAB: 'All Events',
  TODAY_TAB: 'Today',
  MY_EVENT_BADGE: 'My Event',
  MATCH_EMOJI: '📅',
  MATCH_LABEL: 'Match:',
  CLOCK_EMOJI: '⏰',
  REG_DEADLINE_SHORT: 'Reg. Deadline:',
  LOCATION_EMOJI: '📍',
  REGISTRATION_OPEN_CHECK: '✅ Registration Open',
  REGISTRATION_CLOSED_WARNING: '⚠️ Registration Closed',
  PARTICIPANTS_LOWERCASE: 'participants',
  EMPTY_MAILBOX_EMOJI: '📭',

  VALIDATION_ERROR: 'Validation Error',
  INVALID_MATCH_DATE: 'Invalid match date',
  PLATFORM_ANDROID: 'android',
  EVENT_TYPE_SET: 'set',
  FORMAT_1V1: '1v1',
  FORMAT_2V2: '2v2',
  FAILED_TO_UPDATE_EVENT: 'Failed to update event:',
  FAILED_TO_UPDATE_EVENT_MESSAGE: 'Failed to update event. Please try again.',

  MY_EVENTS_FILTER: 'myEvents',
  ALL_FILTER: 'all',
  TODAY_FILTER: 'today',
  UPCOMING_FILTER: 'upcoming',
  DATE_SEPARATOR: 'T',
  ALERT_STYLE_CANCEL: 'cancel',
  ALERT_STYLE_DESTRUCTIVE: 'destructive',
  SCREEN_CREATE_EVENT: 'CreateEvent',
  SCREEN_EVENT_DETAILS: 'EventDetails',
  SCREEN_EDIT_EVENT: 'EditEvent',
  TAP_PLUS_CREATE_FIRST_EVENT: 'Tap + button to create your first event',
  TAP_PLUS_CREATE_EVENT: 'Tap + button to create an event',
  CHECK_BACK_LATER: 'Check back later for new events',

  FAILED_TO_LOAD_USER_STATUS: 'Failed to load user status:',
  SCREEN_INDIVIDUAL_REGISTRATION: 'IndividualRegistration',
  SCREEN_MY_TEAMS: 'MyTeams',
  SCREEN_MY_REGISTRATIONS: 'MyRegistrations',
  SCREEN_FIXTURE_CREATION: 'FixtureCreation',
  STATUS_IN_TEAM: 'in_team',
  STATUS_APPROVED_LOWERCASE: 'approved',
  STATUS_PENDING_LOWERCASE: 'pending',
  STATUS_REJECTED_LOWERCASE: 'rejected',
  STATUS_NOT_REGISTERED: 'not_registered',

  FAILED_TO_LOAD_EVENTS: 'Failed to load events',
  FAILED_TO_CREATE_EVENT: 'Failed to create event',
  FAILED_TO_DELETE_EVENT: 'Failed to delete event',

  FAILED_TO_LOAD_REGISTRATIONS: 'Failed to load registrations:',
  FAILED_TO_LOAD_REGISTRATIONS_MESSAGE: 'Failed to load registrations',
  FORMAT_FULL_TITLE: 'Format Full',
  FORMAT_FULL_MESSAGE: 'This format has reached maximum capacity. Cannot approve more registrations.',
  FAILED_TO_APPROVE_REGISTRATION: 'Failed to approve registration',
  PROVIDE_REJECTION_REASON: 'Please provide a reason for rejection',
  FAILED_TO_REJECT_REGISTRATION: 'Failed to reject registration',
  NO_PENDING_TO_APPROVE: 'There are no pending registrations to approve',
  BULK_APPROVE_TITLE: 'Bulk Approve',
  BULK_APPROVE_MESSAGE: (count: number) => `Approve ${count} pending registrations?`,
  BULK_APPROVE_COMPLETE: 'Bulk Approve Complete',
  BULK_APPROVE_RESULT: (success: number, fail: number) => `Approved: ${success}\nFailed/Full: ${fail}`,
  SCREEN_CREATE_TEAMS: 'CreateTeams',

  FAILED_TO_LOAD_YOUR_REGISTRATIONS: 'Failed to load your registrations',
  CANCEL_REGISTRATION_MESSAGE: (eventTitle: string) => `Are you sure you want to cancel your registration for ${eventTitle}?`,
  THIS_EVENT: 'this event',
  YES_CANCEL: 'Yes, Cancel',
  FAILED_TO_CANCEL_REGISTRATION: 'Failed to cancel registration',
  SCREEN_EVENT_LIST: 'EventList',
  ICON_CHECK_CIRCLE: 'check-circle',
  ICON_SCHEDULE: 'schedule',
  ICON_CANCEL: 'cancel',
  ICON_HELP: 'help',

  SCREEN_LOGIN: 'Login',
  SCREEN_TEAM_REGISTRATIONS: 'TeamRegistrations',
  SCREEN_SCHEDULES_RESULTS: 'SchedulesResults',
  MY_EVENTS_SUBTITLE: 'Events created by you',
  ALL_EVENTS_MENU: 'All Events',
  ALL_EVENTS_SUBTITLE: 'View all platform events',
  TEAM_REG_SUBTITLE: 'View and approve registrations',
  SCHEDULE_RESULT_SUBTITLE: 'Manage schedules and results',
  ICON_EVENT_AVAILABLE: 'event-available',
  ICON_EVENT: 'event',
  ICON_HOW_TO_REG: 'how-to-reg',
  ICON_CALENDAR_TODAY: 'calendar-today',
  EVENTS_DASHBOARD_READY: 'Events dashboard ready',
  ACTIVE_EVENTS_COUNT: (count: number) => `You have ${count} active event${count !== 1 ? 's' : ''}`,
  REGISTRATIONS_RECEIVED: 'Registrations received',
  PARTICIPANTS_REGISTERED_COUNT: (count: number) => `${count} participant${count !== 1 ? 's' : ''} registered across your events`,
  READY_TO_GET_STARTED: 'Ready to get started?',
  CREATE_FIRST_EVENT_PROMPT: 'Create your first event to begin organizing',

  ENTER_VALID_EMAIL: 'Please enter a valid email address',
  FORGOT_PASSWORD_ERROR: 'Forgot password error:',

  SUCCESS_EXCLAIM: 'Success!',
  INDIVIDUAL_COMPETITION: 'Individual competition',
  TEAMS_OF_TWO_ORGANIZER: 'Teams of 2 (created by organizer)',

  FILL_ALL_FIELDS: 'Please fill in all fields',
  LOGIN_ERROR: 'Login error:',
  LOGIN_FAILED_MESSAGE: 'Login failed',
  FAILED_TO_RESET_PASSWORD: 'Failed to reset password',

  SPORT_TYPE_CHESS: 'chess',
  SPORT_TYPE_FOOSBALL: 'foosball',

  CREATE_FORMAT: 'Please create events with formats first before creating teams.',
  SCREEN_MANAGE_REGISTRATIONS: 'ManageRegistrations',
  SCREEN_USER_MANAGEMENT: 'UserManagement',
  SCREEN_TEAM_MANAGEMENT: 'TeamManagement',
  SCREEN_REPORTS: 'Reports',
  SCREEN_SYSTEM_CONFIG: 'SystemConfig',
  ICON_PEOPLE: 'people',
  ICON_GROUP: 'group',
  ICON_ASSESSMENT: 'assessment',
  ICON_SETTINGS: 'settings',
  MANAGE_REG: 'Manage Registrations',
  APPROVE_OR_REJECT: 'Approve/reject participants',
  FORM_TEAMS: 'Form teams from participants',
  MANAGE_USER_ACC: 'Manage user accounts',
  VIEW_TEAM_REG: 'View team registrations',
  MATCH_SCHEDULE: 'Match schedules & results',
  VIEW_ANALYTICS: 'View analytics & reports',
  SYSTEM_CONFIGERATION: 'System configuration',

  ICON_CHEVRON_RIGHT: 'chevron-right',
  ICON_LOGOUT: 'logout',
  ICON_CLOSE: 'close',
  ICON_EVENT_BUSY: 'event-busy',
  TOTAL_USERS_COUNT: '100',
  OPACITY_20: '20',
  ANIMATION_SLIDE: 'slide',
};

export const headerStrings = {
  NOTIFICATIONS: 'Notifications',
  PROFILE: 'Profile',
  SETTINGS: 'Settings',
  SEARCH: 'Search',
  FILTER: 'Filter',
  ADD: 'Add',
  CANCEL: 'Cancel',
  EDIT: 'Edit',
  DELETE: 'Delete',
  SHARE: 'Share',
  BACK: 'Back',
  MENU: 'Menu',
  LOGOUT: 'Logout',
  LOGOUT_MSG: 'Are you sure you want to logout?',

  EVENTS_LIST: 'Events',
  EVENT_DETAILS: 'Event Details',
  CREATE_EVENT: 'Create Event',
  EDIT_EVENT: 'Edit Event',
  MY_EVENTS: 'My Events',
  TEAMS: 'Teams',
  SCHEDULE: 'Schedule',
  REPORTS: 'Reports',
  USERS: 'Users',
  MANAGE_REGISTRATIONS: 'Manage Registrations',
  CREATE_TEAMS: 'Create Teams',
  MY_REGISTRATIONS: 'My Registrations',
  MY_MATCHES: 'My Matches',
  MY_TEAMS: 'My Teams',
  USER_MANAGEMENT: 'User Management',
  TEAM_MANAGEMENT: 'Team Management',
  FORMAT : 'Format',
  NO_EVENTS: 'No Events Available',
  NO_TEAMS: 'No Teams Available',
  NO_MATCHES: 'No Matches Available',
  NO_REGISTRATIONS: 'No Registrations Available',

  BACK_BUTTON: 'Go back',
  MENU_BUTTON: 'Open menu',
  SEARCH_BUTTON: 'Search',
  NOTIFICATION_BUTTON: 'View notifications',
  PROFILE_BUTTON: 'View profile',
  ADD_BUTTON: 'Add new',
  EDIT_BUTTON: 'Edit',
  DELETE_BUTTON: 'Delete',
  SHARE_BUTTON: 'Share',
  FILTER_BUTTON: 'Filter',
  SETTINGS_BUTTON: 'Settings',
};